# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Blinders Chess Assistant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Blinders Chess Assistant
pod 'SwiftSpeech'

  target 'Blinders Chess AssistantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Blinders Chess AssistantUITests' do
    # Pods for testing
  end

end
